title: Exploring the Use of Automated API Migrating Techniques in Practice; An Experience Report on Android
description: Maxime Lamothe, Weiyi Shang
show_downloads: False
google_analytics:
theme: jekyll-theme-slate
